spring.application.name=Joyarta

server.port = 8080

spring.datasource.url = jdbc:mariadb://localhost:3306/jpa
spring.datasource.username=luis
spring.datasource.password=luis

spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=true
spring.codec.max-in-memory-size=20MB